### ISSUE TITLE
Question: How do I use a local font?

### ISSUE THREAD

**Issue by bionictoothpick** [mickr777/textfontimage#1]
How could I put a local path where the ttf font exists?

C:\downloads\fonts\funny.ttf

**Comment by mickr777** [comment]
At the moment you cant, but will be working on it soon and I am also trying to get a dropdown box to show fonts in the cache folder

**Comment by mickr777** [comment]
just added local font path please test, I only have invokeai on Linux and it works there, error handling is a little rough at the moment,  if you get "attribute error" in ui it means your font path is wrong

**Comment by mickr777** [comment]
Added font dropdown for fonts in font_cache folder too
